
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D203",
    "D212",
    "D213",
    "D407",
    "D412",
    "D417",
]
line-length = 88
select = [
    "C9",
    "D",
    "E",
    "F",
    "S",
    "W",
]

[mccabe]
max-complexity = 8

[per-file-ignores]
"*tests/*" = [
    "D205",
    "D400",
    "D401",
    "S101",
    "S106",
    "E501",
    "E731",
]
"*/settings.py" = [
    "F403",
    "F405",
]
"*/migrations/*" = ["E501"]
"*/settings/*" = [
    "F403",
    "F405",
]
